export const initialSections = [
  {
    num: 13,
    local: "ESCOLA FUNDAMENTAL SANTO ANTONIO",
    eleitores: 213,
    zona: "RURAL",
    closed: false,
    votos: {
      22: 0,
      40: 0,
      77: 0,
      27: 0,
      outros: 0,
    },
  },
  {
    num: 14,
    local: "ESCOLA FUNDAMENTAL SANTO ANTONIO",
    eleitores: 213,
    zona: "RURAL",
    closed: false,
    votos: {
      22: 0,
      40: 0,
      77: 0,
      27: 0,
      outros: 0,
    },
  },
  {
    num: 15,
    local: "ESCOLA DE ENS FUND VILA NOVA",
    eleitores: 312,
    zona: "RURAL",
    closed: false,
    votos: {
      22: 0,
      40: 0,
      77: 0,
      27: 0,
      outros: 0,
    },
  },
  {
    num: 36,
    local: "ESC MUN RUI BARBOSA (VILA BOA ESPERANCA)",
    eleitores: 167,
    zona: "RURAL",
    closed: false,
    votos: {
      22: 0,
      40: 0,
      77: 0,
      27: 0,
      outros: 0,
    },
  },
  {
    num: 70,
    local: "ESC MUN RUI BARBOSA (VILA BOA ESPERANCA)",
    eleitores: 168,
    zona: "RURAL",
    closed: false,
    votos: {
      22: 0,
      40: 0,
      77: 0,
      27: 0,
      outros: 0,
    },
  },
  {
    num: 37,
    local: "ESC ENSINO FUNDAMENTAL VILA UNIAO",
    eleitores: 218,
    zona: "RURAL",
    closed: false,
    votos: {
      22: 0,
      40: 0,
      77: 0,
      27: 0,
      outros: 0,
    },
  },
  {
    num: 38,
    local: "ESC ENSINO FUNDAMENTAL VILA UNIAO",
    eleitores: 185,
    zona: "RURAL",
    closed: false,
    votos: {
      22: 0,
      40: 0,
      77: 0,
      27: 0,
      outros: 0,
    },
  },
  {
    num: 39,
    local: "ESC ENSINO FUNDAMENTAL VILA UNIAO",
    eleitores: 184,
    zona: "RURAL",
    closed: false,
    votos: {
      22: 0,
      40: 0,
      77: 0,
      27: 0,
      outros: 0,
    },
  },
  {
    num: 90,
    local: "ESC ENSINO FUNDAMENTAL VILA UNIAO",
    eleitores: 203,
    zona: "RURAL",
    closed: false,
    votos: {
      22: 0,
      40: 0,
      77: 0,
      27: 0,
      outros: 0,
    },
  },
  {
    num: 131,
    local: "ESC ENSINO FUNDAMENTAL VILA UNIAO",
    eleitores: 348,
    zona: "RURAL",
    closed: false,
    votos: {
      22: 0,
      40: 0,
      77: 0,
      27: 0,
      outros: 0,
    },
  },
  {
    num: 132,
    local: "ESC ENSINO FUNDAMENTAL VILA UNIAO",
    eleitores: 84,
    zona: "RURAL",
    closed: false,
    votos: {
      22: 0,
      40: 0,
      77: 0,
      27: 0,
      outros: 0,
    },
  },
  {
    num: 40,
    local: "ESC ENSINO FUNDAMENTAL PORTAO",
    eleitores: 238,
    zona: "RURAL",
    closed: false,
    votos: {
      22: 0,
      40: 0,
      77: 0,
      27: 0,
      outros: 0,
    },
  },
  {
    num: 41,
    local: "ESC ENSINO FUNDAMENTAL PORTAO",
    eleitores: 193,
    zona: "RURAL",
    closed: false,
    votos: {
      22: 0,
      40: 0,
      77: 0,
      27: 0,
      outros: 0,
    },
  },
  {
    num: 100,
    local: "ESC ENSINO FUNDAMENTAL PORTAO",
    eleitores: 300,
    zona: "RURAL",
    closed: false,
    votos: {
      22: 0,
      40: 0,
      77: 0,
      27: 0,
      outros: 0,
    },
  },
  {
    num: 42,
    local: "ESC FUND SOFIA JORGE CRUZ (TRES RAIZES)",
    eleitores: 138,
    zona: "RURAL",
    closed: false,
    votos: {
      22: 0,
      40: 0,
      77: 0,
      27: 0,
      outros: 0,
    },
  },
  {
    num: 105,
    local: "ESC FUND SOFIA JORGE CRUZ (TRES RAIZES)",
    eleitores: 287,
    zona: "RURAL",
    closed: false,
    votos: {
      22: 0,
      40: 0,
      77: 0,
      27: 0,
      outros: 0,
    },
  },
  {
    num: 48,
    local: "UNID ESCOLAR SEVERO SOARES (CR ALMEIDA)",
    eleitores: 230,
    zona: "RURAL",
    closed: false,
    votos: {
      22: 0,
      40: 0,
      77: 0,
      27: 0,
      outros: 0,
    },
  },
  {
    num: 49,
    local: "UNID ESCOLAR SEVERO SOARES (CR ALMEIDA)",
    eleitores: 224,
    zona: "RURAL",
    closed: false,
    votos: {
      22: 0,
      40: 0,
      77: 0,
      27: 0,
      outros: 0,
    },
  },
  {
    num: 72,
    local: "UNID ESCOLAR SEVERO SOARES (CR ALMEIDA)",
    eleitores: 229,
    zona: "RURAL",
    closed: false,
    votos: {
      22: 0,
      40: 0,
      77: 0,
      27: 0,
      outros: 0,
    },
  },
  {
    num: 77,
    local: "ESC ENS FUND FAIXA DO CLOVES",
    eleitores: 271,
    zona: "RURAL",
    closed: false,
    votos: {
      22: 0,
      40: 0,
      77: 0,
      27: 0,
      outros: 0,
    },
  },
  {
    num: 74,
    local: "ESC ENS FUND FAIXA SÃO SEBASTIAO",
    eleitores: 268,
    zona: "RURAL",
    closed: false,
    votos: {
      22: 0,
      40: 0,
      77: 0,
      27: 0,
      outros: 0,
    },
  },
  {
    num: 75,
    local: "ESC ENS FUND FAIXA SÃO JORGE",
    eleitores: 207,
    zona: "RURAL",
    closed: false,
    votos: {
      22: 0,
      40: 0,
      77: 0,
      27: 0,
      outros: 0,
    },
  },
  {
    num: 76,
    local: "ESC ENS FUND COCAL",
    eleitores: 217,
    zona: "RURAL",
    closed: false,
    votos: {
      22: 0,
      40: 0,
      77: 0,
      27: 0,
      outros: 0,
    },
  },
  {
    num: 83,
    local: "ESC ENS FUNDMENTAL BACURI",
    eleitores: 189,
    zona: "RURAL",
    closed: false,
    votos: {
      22: 0,
      40: 0,
      77: 0,
      27: 0,
      outros: 0,
    },
  },
  {
    num: 86,
    local: "ESC ENS FUNDAMENTAL SETE VOLTAS",
    eleitores: 83,
    zona: "RURAL",
    closed: false,
    votos: {
      22: 0,
      40: 0,
      77: 0,
      27: 0,
      outros: 0,
    },
  },
  {
    num: 88,
    local: "ESC ENS FUND N SEN DE FATIMA (MACAXEIRA)",
    eleitores: 142,
    zona: "RURAL",
    closed: false,
    votos: {
      22: 0,
      40: 0,
      77: 0,
      27: 0,
      outros: 0,
    },
  },
  {
    num: 94,
    local: "ESC ENS FUND MIGUEL PEREIRA (QUADRA X)",
    eleitores: 103,
    zona: "RURAL",
    closed: false,
    votos: {
      22: 0,
      40: 0,
      77: 0,
      27: 0,
      outros: 0,
    },
  },
  {
    num: 16,
    local: "ESCOLA DE ENS FUND FUTURO FELIZ",
    eleitores: 263,
    zona: "URBANA",
    closed: false,
    votos: {
      22: 0,
      40: 0,
      77: 0,
      27: 0,
      outros: 0,
    },
  },
  {
    num: 17,
    local: "ESCOLA DE ENS FUND FUTURO FELIZ",
    eleitores: 260,
    zona: "URBANA",
    closed: false,
    votos: {
      22: 0,
      40: 0,
      77: 0,
      27: 0,
      outros: 0,
    },
  },
  {
    num: 18,
    local: "ESCOLA DE ENS FUND FUTURO FELIZ",
    eleitores: 267,
    zona: "URBANA",
    closed: false,
    votos: {
      22: 0,
      40: 0,
      77: 0,
      27: 0,
      outros: 0,
    },
  },
  {
    num: 19,
    local: "ESCOLA DE ENS FUND FUTURO FELIZ",
    eleitores: 259,
    zona: "URBANA",
    closed: false,
    votos: {
      22: 0,
      40: 0,
      77: 0,
      27: 0,
      outros: 0,
    },
  },
  {
    num: 20,
    local: "ESCOLA DE ENS FUND FUTURO FELIZ",
    eleitores: 268,
    zona: "URBANA",
    closed: false,
    votos: {
      22: 0,
      40: 0,
      77: 0,
      27: 0,
      outros: 0,
    },
  },
  {
    num: 109,
    local: "ESCOLA DE ENS FUND FUTURO FELIZ",
    eleitores: 345,
    zona: "URBANA",
    closed: false,
    votos: {
      22: 0,
      40: 0,
      77: 0,
      27: 0,
      outros: 0,
    },
  },
  {
    num: 128,
    local: "ESCOLA DE ENS FUND FUTURO FELIZ",
    eleitores: 346,
    zona: "URBANA",
    closed: false,
    votos: {
      22: 0,
      40: 0,
      77: 0,
      27: 0,
      outros: 0,
    },
  },
  {
    num: 21,
    local: "ESCOLA GOV NUNES FREIRE",
    eleitores: 327,
    zona: "URBANA",
    closed: false,
    votos: {
      22: 0,
      40: 0,
      77: 0,
      27: 0,
      outros: 0,
    },
  },
  {
    num: 22,
    local: "ESCOLA GOV NUNES FREIRE",
    eleitores: 279,
    zona: "URBANA",
    closed: false,
    votos: {
      22: 0,
      40: 0,
      77: 0,
      27: 0,
      outros: 0,
    },
  },
  {
    num: 23,
    local: "ESCOLA GOV NUNES FREIRE",
    eleitores: 286,
    zona: "URBANA",
    closed: false,
    votos: {
      22: 0,
      40: 0,
      77: 0,
      27: 0,
      outros: 0,
    },
  },
  {
    num: 24,
    local: "ESCOLA GOV NUNES FREIRE",
    eleitores: 284,
    zona: "URBANA",
    closed: false,
    votos: {
      22: 0,
      40: 0,
      77: 0,
      27: 0,
      outros: 0,
    },
  },
  {
    num: 25,
    local: "ESCOLA GOV NUNES FREIRE",
    eleitores: 282,
    zona: "URBANA",
    closed: false,
    votos: {
      22: 0,
      40: 0,
      77: 0,
      27: 0,
      outros: 0,
    },
  },
  {
    num: 26,
    local: "ESCOLA GOV NUNES FREIRE",
    eleitores: 293,
    zona: "URBANA",
    closed: false,
    votos: {
      22: 0,
      40: 0,
      77: 0,
      27: 0,
      outros: 0,
    },
  },
  {
    num: 27,
    local: "ESCOLA GOV NUNES FREIRE",
    eleitores: 282,
    zona: "URBANA",
    closed: false,
    votos: {
      22: 0,
      40: 0,
      77: 0,
      27: 0,
      outros: 0,
    },
  },
  {
    num: 28,
    local: "ESCOLA GOV NUNES FREIRE",
    eleitores: 282,
    zona: "URBANA",
    closed: false,
    votos: {
      22: 0,
      40: 0,
      77: 0,
      27: 0,
      outros: 0,
    },
  },
  {
    num: 29,
    local: "ESCOLA RURAL",
    eleitores: 322,
    zona: "URBANA",
    closed: false,
    votos: {
      22: 0,
      40: 0,
      77: 0,
      27: 0,
      outros: 0,
    },
  },
  {
    num: 30,
    local: "ESCOLA RURAL",
    eleitores: 294,
    zona: "URBANA",
    closed: false,
    votos: {
      22: 0,
      40: 0,
      77: 0,
      27: 0,
      outros: 0,
    },
  },
  {
    num: 31,
    local: "ESCOLA RURAL",
    eleitores: 297,
    zona: "URBANA",
    closed: false,
    votos: {
      22: 0,
      40: 0,
      77: 0,
      27: 0,
      outros: 0,
    },
  },
  {
    num: 32,
    local: "ESCOLA RURAL",
    eleitores: 285,
    zona: "URBANA",
    closed: false,
    votos: {
      22: 0,
      40: 0,
      77: 0,
      27: 0,
      outros: 0,
    },
  },
  {
    num: 33,
    local: "ESCOLA RURAL",
    eleitores: 295,
    zona: "URBANA",
    closed: false,
    votos: {
      22: 0,
      40: 0,
      77: 0,
      27: 0,
      outros: 0,
    },
  },
  {
    num: 34,
    local: "ESCOLA RURAL",
    eleitores: 290,
    zona: "URBANA",
    closed: false,
    votos: {
      22: 0,
      40: 0,
      77: 0,
      27: 0,
      outros: 0,
    },
  },
  {
    num: 35,
    local: "ESCOLA RURAL",
    eleitores: 288,
    zona: "URBANA",
    closed: false,
    votos: {
      22: 0,
      40: 0,
      77: 0,
      27: 0,
      outros: 0,
    },
  },
  {
    num: 43,
    local: "COMP EDUCACIONAL HAMILTON WERNECK",
    eleitores: 267,
    zona: "URBANA",
    closed: false,
    votos: {
      22: 0,
      40: 0,
      77: 0,
      27: 0,
      outros: 0,
    },
  },
  {
    num: 44,
    local: "COMP EDUCACIONAL HAMILTON WERNECK",
    eleitores: 263,
    zona: "URBANA",
    closed: false,
    votos: {
      22: 0,
      40: 0,
      77: 0,
      27: 0,
      outros: 0,
    },
  },
  {
    num: 45,
    local: "COMP EDUCACIONAL HAMILTON WERNECK",
    eleitores: 261,
    zona: "URBANA",
    closed: false,
    votos: {
      22: 0,
      40: 0,
      77: 0,
      27: 0,
      outros: 0,
    },
  },
  {
    num: 46,
    local: "COMP EDUCACIONAL HAMILTON WERNECK",
    eleitores: 263,
    zona: "URBANA",
    closed: false,
    votos: {
      22: 0,
      40: 0,
      77: 0,
      27: 0,
      outros: 0,
    },
  },
  {
    num: 47,
    local: "COMP EDUCACIONAL HAMILTON WERNECK",
    eleitores: 254,
    zona: "URBANA",
    closed: false,
    votos: {
      22: 0,
      40: 0,
      77: 0,
      27: 0,
      outros: 0,
    },
  },
  {
    num: 79,
    local: "COMP EDUCACIONAL HAMILTON WERNECK",
    eleitores: 260,
    zona: "URBANA",
    closed: false,
    votos: {
      22: 0,
      40: 0,
      77: 0,
      27: 0,
      outros: 0,
    },
  },
  {
    num: 89,
    local: "COMP EDUCACIONAL HAMILTON WERNECK",
    eleitores: 258,
    zona: "URBANA",
    closed: false,
    votos: {
      22: 0,
      40: 0,
      77: 0,
      27: 0,
      outros: 0,
    },
  },
  {
    num: 103,
    local: "COMP EDUCACIONAL HAMILTON WERNECK",
    eleitores: 338,
    zona: "URBANA",
    closed: false,
    votos: {
      22: 0,
      40: 0,
      77: 0,
      27: 0,
      outros: 0,
    },
  },
  {
    num: 81,
    local: "ESCOLA ANTONIO TORRES",
    eleitores: 308,
    zona: "URBANA",
    closed: false,
    votos: {
      22: 0,
      40: 0,
      77: 0,
      27: 0,
      outros: 0,
    },
  },
  {
    num: 91,
    local: "ESCOLA ANTONIO TORRES",
    eleitores: 294,
    zona: "URBANA",
    closed: false,
    votos: {
      22: 0,
      40: 0,
      77: 0,
      27: 0,
      outros: 0,
    },
  },
  {
    num: 99,
    local: "ESCOLA ANTONIO TORRES",
    eleitores: 318,
    zona: "URBANA",
    closed: false,
    votos: {
      22: 0,
      40: 0,
      77: 0,
      27: 0,
      outros: 0,
    },
  },
  {
    num: 117,
    local: "ESCOLA ANTONIO TORRES",
    eleitores: 361,
    zona: "URBANA",
    closed: false,
    votos: {
      22: 0,
      40: 0,
      77: 0,
      27: 0,
      outros: 0,
    },
  },
  {
    num: 96,
    local: "UNID INTEGRADA PAULO FREIRE",
    eleitores: 263,
    zona: "URBANA",
    closed: false,
    votos: {
      22: 0,
      40: 0,
      77: 0,
      27: 0,
      outros: 0,
    },
  },
  {
    num: 98,
    local: "UNID INTEGRADA PAULO FREIRE",
    eleitores: 274,
    zona: "URBANA",
    closed: false,
    votos: {
      22: 0,
      40: 0,
      77: 0,
      27: 0,
      outros: 0,
    },
  },
  {
    num: 124,
    local: "UNID INTEGRADA PAULO FREIRE",
    eleitores: 328,
    zona: "URBANA",
    closed: false,
    votos: {
      22: 0,
      40: 0,
      77: 0,
      27: 0,
      outros: 0,
    },
  },
  {
    num: 110,
    local: "UNID ESCOLAR ALCINO GOMES",
    eleitores: 344,
    zona: "URBANA",
    closed: false,
    votos: {
      22: 0,
      40: 0,
      77: 0,
      27: 0,
      outros: 0,
    },
  },
  {
    num: 123,
    local: "UNID ESCOLAR ALCINO GOMES",
    eleitores: 343,
    zona: "URBANA",
    closed: false,
    votos: {
      22: 0,
      40: 0,
      77: 0,
      27: 0,
      outros: 0,
    },
  },
  {
    num: 133,
    local: "UNID ESCOLAR ALCINO GOMES",
    eleitores: 270,
    zona: "URBANA",
    closed: false,
    votos: {
      22: 0,
      40: 0,
      77: 0,
      27: 0,
      outros: 0,
    },
  },
  {
    num: 111,
    local: "UNID ENS FUND FERREIRA GULLAR",
    eleitores: 349,
    zona: "URBANA",
    closed: false,
    votos: {
      22: 0,
      40: 0,
      77: 0,
      27: 0,
      outros: 0,
    },
  },
  {
    num: 134,
    local: "UNID ENS FUND FERREIRA GULLAR",
    eleitores: 17,
    zona: "URBANA",
  },
];
