const data = [
  {
    numero: 13,
    local: "ESCOLA FUNDAMENTAL SANTO ANTONIO",
    eleitores: 213,
    zona: "rural",
    totalizada: false,
  },
  {
    numero: 14,
    local: "ESCOLA FUNDAMENTAL SANTO ANTONIO",
    eleitores: 213,
    zona: "rural",
    totalizada: false,
  },
  {
    numero: 15,
    local: "ESCOLA DE ENS FUND VILA NOVA",
    eleitores: 312,
    zona: "rural",
    totalizada: false,
  },
  {
    numero: 36,
    local: "ESC MUN RUI BARBOSA (VILA BOA ESPERANCA)",
    eleitores: 167,
    zona: "rural",
    totalizada: false,
  },
  {
    numero: 70,
    local: "ESC MUN RUI BARBOSA (VILA BOA ESPERANCA)",
    eleitores: 168,
    zona: "rural",
    totalizada: false,
  },
  {
    numero: 37,
    local: "ESC ENSINO FUNDAMENTAL VILA UNIAO",
    eleitores: 218,
    zona: "rural",
    totalizada: false,
  },
  {
    numero: 38,
    local: "ESC ENSINO FUNDAMENTAL VILA UNIAO",
    eleitores: 185,
    zona: "rural",
    totalizada: false,
  },
  {
    numero: 39,
    local: "ESC ENSINO FUNDAMENTAL VILA UNIAO",
    eleitores: 184,
    zona: "rural",
    totalizada: false,
  },
  {
    numero: 90,
    local: "ESC ENSINO FUNDAMENTAL VILA UNIAO",
    eleitores: 203,
    zona: "rural",
    totalizada: false,
  },
  {
    numero: 131,
    local: "ESC ENSINO FUNDAMENTAL VILA UNIAO",
    eleitores: 348,
    zona: "rural",
    totalizada: false,
  },
  {
    numero: 132,
    local: "ESC ENSINO FUNDAMENTAL VILA UNIAO",
    eleitores: 84,
    zona: "rural",
    totalizada: false,
  },
  {
    numero: 40,
    local: "ESC ENSINO FUNDAMENTAL PORTAO",
    eleitores: 238,
    zona: "rural",
    totalizada: false,
  },
  {
    numero: 41,
    local: "ESC ENSINO FUNDAMENTAL PORTAO",
    eleitores: 193,
    zona: "rural",
    totalizada: false,
  },
  {
    numero: 100,
    local: "ESC ENSINO FUNDAMENTAL PORTAO",
    eleitores: 300,
    zona: "rural",
    totalizada: false,
  },
  {
    numero: 42,
    local: "ESC FUND SOFIA JORGE CRUZ (TRES RAIZES)",
    eleitores: 138,
    zona: "rural",
    totalizada: false,
  },
  {
    numero: 105,
    local: "ESC FUND SOFIA JORGE CRUZ (TRES RAIZES)",
    eleitores: 287,
    zona: "rural",
    totalizada: false,
  },
  {
    numero: 48,
    local: "UNID ESCOLAR SEVERO SOARES (CR ALMEIDA)",
    eleitores: 230,
    zona: "rural",
    totalizada: false,
  },
  {
    numero: 49,
    local: "UNID ESCOLAR SEVERO SOARES (CR ALMEIDA)",
    eleitores: 224,
    zona: "rural",
    totalizada: false,
  },
  {
    numero: 72,
    local: "UNID ESCOLAR SEVERO SOARES (CR ALMEIDA)",
    eleitores: 229,
    zona: "rural",
    totalizada: false,
  },
  {
    numero: 77,
    local: "ESC ENS FUND FAIXA DO CLOVES",
    eleitores: 271,
    zona: "rural",
    totalizada: false,
  },
  {
    numero: 74,
    local: "ESC ENS FUND FAIXA SÃO SEBASTIAO",
    eleitores: 268,
    zona: "rural",
    totalizada: false,
  },
  {
    numero: 75,
    local: "ESC ENS FUND FAIXA SÃO JORGE",
    eleitores: 207,
    zona: "rural",
    totalizada: false,
  },
  {
    numero: 76,
    local: "ESC ENS FUND COCAL",
    eleitores: 217,
    zona: "rural",
    totalizada: false,
  },
  {
    numero: 83,
    local: "ESC ENS FUNDMENTAL BACURI",
    eleitores: 189,
    zona: "rural",
    totalizada: false,
  },
  {
    numero: 86,
    local: "ESC ENS FUNDAMENTAL SETE VOLTAS",
    eleitores: 83,
    zona: "rural",
    totalizada: false,
  },
  {
    numero: 88,
    local: "ESC ENS FUND N SEN DE FATIMA (MACAXEIRA)",
    eleitores: 142,
    zona: "rural",
    totalizada: false,
  },
  {
    numero: 94,
    local: "ESC ENS FUND MIGUEL PEREIRA (QUADRA X)",
    eleitores: 103,
    zona: "rural",
    totalizada: false,
  },
  {
    numero: 16,
    local: "ESCOLA DE ENS FUND FUTURO FELIZ",
    eleitores: 263,
    zona: "urbana",
    totalizada: false,
  },
  {
    numero: 17,
    local: "ESCOLA DE ENS FUND FUTURO FELIZ",
    eleitores: 260,
    zona: "urbana",
    totalizada: false,
  },
  {
    numero: 18,
    local: "ESCOLA DE ENS FUND FUTURO FELIZ",
    eleitores: 267,
    zona: "urbana",
    totalizada: false,
  },
  {
    numero: 19,
    local: "ESCOLA DE ENS FUND FUTURO FELIZ",
    eleitores: 259,
    zona: "urbana",
    totalizada: false,
  },
  {
    numero: 20,
    local: "ESCOLA DE ENS FUND FUTURO FELIZ",
    eleitores: 268,
    zona: "urbana",
    totalizada: false,
  },
  {
    numero: 109,
    local: "ESCOLA DE ENS FUND FUTURO FELIZ",
    eleitores: 345,
    zona: "urbana",
    totalizada: false,
  },
  {
    numero: 128,
    local: "ESCOLA DE ENS FUND FUTURO FELIZ",
    eleitores: 346,
    zona: "urbana",
    totalizada: false,
  },
  {
    numero: 21,
    local: "ESCOLA GOV NUNES FREIRE",
    eleitores: 327,
    zona: "urbana",
    totalizada: false,
  },
  {
    numero: 22,
    local: "ESCOLA GOV NUNES FREIRE",
    eleitores: 279,
    zona: "urbana",
    totalizada: false,
  },
  {
    numero: 23,
    local: "ESCOLA GOV NUNES FREIRE",
    eleitores: 286,
    zona: "urbana",
    totalizada: false,
  },
  {
    numero: 24,
    local: "ESCOLA GOV NUNES FREIRE",
    eleitores: 284,
    zona: "urbana",
    totalizada: false,
  },
  {
    numero: 25,
    local: "ESCOLA GOV NUNES FREIRE",
    eleitores: 282,
    zona: "urbana",
    totalizada: false,
  },
  {
    numero: 26,
    local: "ESCOLA GOV NUNES FREIRE",
    eleitores: 293,
    zona: "urbana",
    totalizada: false,
  },
  {
    numero: 27,
    local: "ESCOLA GOV NUNES FREIRE",
    eleitores: 282,
    zona: "urbana",
    totalizada: false,
  },
  {
    numero: 28,
    local: "ESCOLA GOV NUNES FREIRE",
    eleitores: 282,
    zona: "urbana",
    totalizada: false,
  },
  {
    numero: 29,
    local: "ESCOLA rural",
    eleitores: 322,
    zona: "urbana",
    totalizada: false,
  },
  {
    numero: 30,
    local: "ESCOLA rural",
    eleitores: 294,
    zona: "urbana",
    totalizada: false,
  },
  {
    numero: 31,
    local: "ESCOLA rural",
    eleitores: 297,
    zona: "urbana",
    totalizada: false,
  },
  {
    numero: 32,
    local: "ESCOLA rural",
    eleitores: 285,
    zona: "urbana",
    totalizada: false,
  },
  {
    numero: 33,
    local: "ESCOLA rural",
    eleitores: 295,
    zona: "urbana",
    totalizada: false,
  },
  {
    numero: 34,
    local: "ESCOLA rural",
    eleitores: 290,
    zona: "urbana",
    totalizada: false,
  },
  {
    numero: 35,
    local: "ESCOLA rural",
    eleitores: 288,
    zona: "urbana",
    totalizada: false,
  },
  {
    numero: 43,
    local: "COMP EDUCACIONAL HAMILTON WERNECK",
    eleitores: 267,
    zona: "urbana",
    totalizada: false,
  },
  {
    numero: 44,
    local: "COMP EDUCACIONAL HAMILTON WERNECK",
    eleitores: 263,
    zona: "urbana",
    totalizada: false,
  },
  {
    numero: 45,
    local: "COMP EDUCACIONAL HAMILTON WERNECK",
    eleitores: 261,
    zona: "urbana",
    totalizada: false,
  },
  {
    numero: 46,
    local: "COMP EDUCACIONAL HAMILTON WERNECK",
    eleitores: 263,
    zona: "urbana",
    totalizada: false,
  },
  {
    numero: 47,
    local: "COMP EDUCACIONAL HAMILTON WERNECK",
    eleitores: 254,
    zona: "urbana",
    totalizada: false,
  },
  {
    numero: 79,
    local: "COMP EDUCACIONAL HAMILTON WERNECK",
    eleitores: 260,
    zona: "urbana",
    totalizada: false,
  },
  {
    numero: 89,
    local: "COMP EDUCACIONAL HAMILTON WERNECK",
    eleitores: 258,
    zona: "urbana",
    totalizada: false,
  },
  {
    numero: 103,
    local: "COMP EDUCACIONAL HAMILTON WERNECK",
    eleitores: 338,
    zona: "urbana",
    totalizada: false,
  },
  {
    numero: 81,
    local: "ESCOLA ANTONIO TORRES",
    eleitores: 308,
    zona: "urbana",
    totalizada: false,
  },
  {
    numero: 91,
    local: "ESCOLA ANTONIO TORRES",
    eleitores: 294,
    zona: "urbana",
    totalizada: false,
  },
  {
    numero: 99,
    local: "ESCOLA ANTONIO TORRES",
    eleitores: 318,
    zona: "urbana",
    totalizada: false,
  },
  {
    numero: 117,
    local: "ESCOLA ANTONIO TORRES",
    eleitores: 361,
    zona: "urbana",
    totalizada: false,
  },
  {
    numero: 96,
    local: "UNID INTEGRADA PAULO FREIRE",
    eleitores: 263,
    zona: "urbana",
    totalizada: false,
  },
  {
    numero: 98,
    local: "UNID INTEGRADA PAULO FREIRE",
    eleitores: 274,
    zona: "urbana",
    totalizada: false,
  },
  {
    numero: 124,
    local: "UNID INTEGRADA PAULO FREIRE",
    eleitores: 328,
    zona: "urbana",
    totalizada: false,
  },
  {
    numero: 110,
    local: "UNID ESCOLAR ALCINO GOMES",
    eleitores: 344,
    zona: "urbana",
    totalizada: false,
  },
  {
    numero: 123,
    local: "UNID ESCOLAR ALCINO GOMES",
    eleitores: 343,
    zona: "urbana",
    totalizada: false,
  },
  {
    numero: 133,
    local: "UNID ESCOLAR ALCINO GOMES",
    eleitores: 270,
    zona: "urbana",
    totalizada: false,
  },
  {
    numero: 111,
    local: "UNID ENS FUND FERREIRA GULLAR",
    eleitores: 349,
    zona: "urbana",
    totalizada: false,
  },
  {
    numero: 134,
    local: "UNID ENS FUND FERREIRA GULLAR",
    eleitores: 17,
    zona: "urbana",
    totalizada: false,
  },
];

export default data;
